[versions]
#Versioning
#version_code = 1
#version_name = '0.0.0'
#build_tools = '30.0.3'

#Sdk and tools
compile_sdk = "36"
target_sdk = "36"
min_sdk = "23"

#Kotlin
kotlin = "2.2.20"
ksp = "2.2.20-2.0.2"
ktx = '1.17.0'
work = '2.4.0'

#Compose
composeBom = "2025.09.00"
compose_activity = "1.11.0"
compose_constraint = '1.1.01'
compose_foundation = "1.9.1"
compose_paging = "3.3.6"
compose_lifecycle = "2.9.3"

#Android dependencies
lifecycle = "2.9.3"
room = "2.8.0"
navigation = "2.9.4"
palette = '1.0.0'

#Accompanist
accompanist = "0.36.0"

#Material Design
material3 = "1.4.0-rc01"
splashscreen = "1.0.1"

#Firebase
firebase = '28.1.0'

#Di
dagger = "2.57.1"
dagger_android = "1.2.0"
koin-bom = "4.1.1"

#Ktor
ktor_bom = "3.3.0"

#Storage
datastore = "1.1.7"

#Tools
timber = '5.0.1'
serialization = "1.9.0"
moshi = "1.15.2"
desugar_jdk = "2.1.5"
secrets = "2.0.1"
coil = "3.3.0"
browser = "1.9.0"

#Testing
junit = "4.13.2"
junitVersion = "1.3.0"
junit_android = '1.1.3'
test_core = '1.4.0'
espresso = '3.7.0'
test_runner = '1.4.0'
mockito = '4.5.0'

# Plugins
agp = "8.13.0"
uiToolingPreviewAndroid = "1.6.7"
uiTooling = "1.7.3"
appcompat = "1.7.1"
material = "1.13.0"
jetbrainsKotlinJvm = "2.2.20"
uiTextGoogleFonts = "1.9.1"
uiGraphicsAndroid = "1.9.1"

[libraries]

#Kotlin
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "ktx" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }

#Android
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }

#Compose
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "compose_activity" }
androidx-lifecycle-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "compose_lifecycle" }

androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
androidx-ui-graphics-android = { group = "androidx.compose.ui", name = "ui-graphics-android", version.ref = "uiGraphicsAndroid" }

androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "compose_constraint" }
androidx-paging-compose = { group = "androidx.paging", name = "paging-compose", version.ref = "compose_paging" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "compose_foundation" }

#Navigation
androidx-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }

#Koin
koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin-bom" }
koin-core = { module = "io.insert-koin:koin-core" }
koin-android = { module = "io.insert-koin:koin-android" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose" }
koin-compose = { module = "io.insert-koin:koin-compose" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-androidx-compose-viewmodel" }
koin-compose-navigation = { module = "io.insert-koin:koin-androidx-compose-navigation" }

#Theming
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
androidx-ui-text-google-fonts = { group = "androidx.compose.ui", name = "ui-text-google-fonts", version.ref = "uiTextGoogleFonts" }
androidx-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "splashscreen"}

#Network
io-ktor-bom = { group = "io.ktor", name = "ktor-bom", version.ref = "ktor_bom" }
io-ktor-client-core = { group = "io.ktor", name = "ktor-client-core" }
io-ktor-client-okhttp = { group = "io.ktor", name = "ktor-client-okhttp" }
io-ktor-client-darwin = { group = "io.ktor", name = "ktor-client-darwin" }
io-ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation" }
io-ktor-client-logging = { group = "io.ktor", name = "ktor-client-logging" }
io-ktor-serialization-kotlinx-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json" }
io-ktor-client-auth = { group = "io.ktor", name = "ktor-client-auth" }

#Room
androidx-room = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
androidx-room-common = { group = "androidx.room", name = "room-common", version.ref = "room" }
androidx-room-paging = { group = "androidx.room", name = "room-paging", version.ref = "room" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }

#Storate
androidx-datastore = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }

#Desugaring
desugar-jdk = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "desugar_jdk" }

#Accompanist
google-accompanist-systemuicontroller = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version.ref = "accompanist" }

#Tools
jakewharton-timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }
io-coil-kt = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }
io-coil-kt-network = { group = "io.coil-kt.coil3", name = "coil-network-okhttp", version.ref = "coil" }
androidx-pallete = { group = "androidx.palette", name = "palette-ktx", version.ref = "palette" }
squareup-moshi = { group = "com.squareup.moshi", name = "moshi-kotlin", version.ref = "moshi" }
squareup-moshi-ksp = { group = "com.squareup.moshi", name = "moshi-kotlin-codegen", version.ref = "moshi" }
androidx-browser = { group = "androidx.browser", name = "browser", version.ref = "browser" }

#Testing
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
google-devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
dagger-hilt = { id = "com.google.dagger.hilt.android", version.ref = "dagger" }
secrets-gradle = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version.ref = "secrets" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }

[bundles]
compose = [
    "androidx-activity-compose",
    "androidx-ui",
    "androidx-ui-graphics",
    "androidx-ui-tooling-preview",
    "androidx-compose-foundation",
    "androidx-icons-extended",
    "androidx-lifecycle-compose",
    "androidx-navigation"
]
koin = [
    "koin-core",
    "koin-android",
    "koin-androidx-compose",
    #    "koin-compose-viewmodel",
    "koin-compose-navigation"
    #    "koin-compose"
]
room = [
    "androidx-room",
    "androidx-room-common",
    "androidx-room-paging"
]
ktor = [
    "io-ktor-client-core",
    "io-ktor-client-okhttp",
    "io-ktor-client-content-negotiation",
    "io-ktor-client-auth",
    "io-ktor-client-logging",
    "io-ktor-serialization-kotlinx-json"
]
coil = [
    "io-coil-kt",
    "io-coil-kt-network"
]
