[versions]
#Versioning
#version_code = 1
#version_name = '0.0.0'
#build_tools = '30.0.3'

#Sdk and tools
compile_sdk = "34"
target_sdk = "34"
min_sdk = "21"

#Kotlin
kotlin = '2.0.0'
coroutines = '1.6.1'
ktx = '1.13.1'
ktlint = '0.30.0'
gradle = '3.5.1'
work = '2.4.0'
ksp = "2.0.0-1.0.21"

#Compose
composeBom = "2024.05.00"
compose_activity = '1.9.0'
compose_constraint = '1.0.1'
compose_foundation = "1.6.7"
compose_paging = "3.3.0"

#Android dependencies
lifecycle = "2.8.1"
room = '2.4.2'
navigation = "2.7.7"
navigation_destination = "1.10.2"
palette = '1.0.0'

#Accompanist
accompanist = '0.34.0'

#Material Design
material3 = '1.2.1'

#Firebase
firebase = '28.1.0'

#Di
dagger = '2.51.1'
dagger_android = "1.2.0"

#Retrofit
retrofit = '2.11.0'
okhttp = "4.12.0"

#Tools
timber = '5.0.1'
moshi = '1.15.1'
desugar_jdk = "2.0.4"
secrets = "2.0.1"
coil = "2.6.0"

#Testing
junit = '4.13.2'
junit_android = '1.1.3'
test_core = '1.4.0'
espresso = '3.5.1'
test_runner = '1.4.0'
mockito = '4.5.0'

# Plugins
agp = "8.4.1"
uiToolingPreviewAndroid = "1.6.7"

[libraries]

#Kotlin
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "ktx" }

#Android
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }

#Compose
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "compose_activity" }

androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }

androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "compose_constraint" }
androidx-paging-compose = { group = "androidx.paging", name = "paging-compose", version.ref = "compose_paging" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "compose_foundation" }

#Navigation
androidx-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }
compose-destinations = { group = "io.github.raamcosta.compose-destinations", name = "core", version.ref = "navigation_destination" }
compose-destinations-ksp = { group = "io.github.raamcosta.compose-destinations", name = "ksp", version.ref = "navigation_destination" }

#Dagger Hilt
dagger-hilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "dagger" }
dagger-hilt-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "dagger_android" }
dagger-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "dagger_android" }
dagger-hilt-kapt = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "dagger" }

#Material
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }

#Network
squareup-retrofit2-retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit"}
squareup-retrofit2-converter-moshi = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "retrofit"}
squareup-okhttp3-okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp"}
squareup-okhttp3-login-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp"}

#Desugaring
desugar-jdk = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "desugar_jdk" }

#Accompanist
google-accompanist-systemuicontroller = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version.ref = "accompanist"}

#Tools
jakewharton-timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }
io-coil-kt = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil"}
androidx-pallete = { group = "androidx.palette", name = "palette-ktx", version.ref = "palette"}
squareup-moshi = { group = "com.squareup.moshi", name = "moshi-kotlin", version.ref = "moshi"}
squareup-moshi-ksp = { group = "com.squareup.moshi", name = "moshi-kotlin-codegen", version.ref = "moshi"}

#Testing
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junit" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
google-devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
dagger-hilt = { id = "com.google.dagger.hilt.android", version.ref = "dagger" }
secrets-gradle = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version.ref = "secrets" }